### PR TITLE
Add TransportStreamOption type and send formated message

### PR DESCRIPTION
**Pull request by mohaalak**
with this pull request you can create `TelegramTransport` with transport stream option type,
also when `format` or `useWinstonLogger` is set it will send the formatted message create by `winston.formatter` to telegra.

### CODE REVIEW

**Comment by ivanmarban** [comment]
Could you please provide some examples about using winston-telegram with TransportStreamOption ?

What are the advantages of adding more formatting options to winston-telegram?

**Comment by mohaalak** [comment]
I've got this format for all of my logs in the root winston logger

```
export const logger = winston.createLogger({
  level: "info",
  format: combine(
    timestamp({ format: "YYYY-MM-DD HH:mm:ss" }),
    splat(),
    winston.format.errors({ stack: true })
  ),
  defaultMeta: { service: process.env.SERVICE_NAME },
});
```

but in `FileTransport` I combine the format with something like `winston.format.prettyPrint()` so after formating all the messages using root format, it will write the logs in json format.

```
 logger.add(new winston.transports.File({
    format: winston.format.prettyPrint(),
  }));
```

but I want to use all the root format with  `myFormat` in telegram transport

```
const myFormat = printf(
  ({ level, message, label, service, timestamp, request, ...meta }) => {
    return `${timestamp} [${service}] [${label}] ${level}: ${message}`;
  }
);
```

now I can use it this way

```
    logger.add(
      new TelegramLogger({
        token,
        chatId: parseInt(chatId),
        level: "warn",
        batchingDelay: 10000,
        parseMode: "",
        format: myFormat,
        useWinstonFormatter: true,
      })
```

in this way I don't have write all the root format again.

**Comment by ivanmarban** [comment]
Thanks for the clarification. I'm going to take a look into _winston_ documentation about _Formats_ and I will consider making a new mayor release of winston-telegram dropping actual formatting options in favour of _Formats_ from winston.

**Comment by mohaalak** [comment]
so I'll close this pull request, please let met know when you add this feature

**Pull request closed without merging**
