### PR TITLE
Add parse mode to options

### PR DESCRIPTION
**Pull request by golubvladimir**
Add parse mode to options for formatting messages.

### CODE REVIEW

**Comment by ivanmarban** [comment]
What is the point of this PR ? I do not see the necesity of formatting messages in Markdown or HTML, as you are adding extra characters to the final message to be sent. This could be a problem with the length of the message.

**Comment by golubvladimir** [comment]
@ivanmarban I want to style the message

```
*name error*: ${ name }
```

**Comment by golubvladimir** [comment]
@ivanmarban 
Will be accepted PR ?

**Comment by ivanmarban** [comment]
Closing this PR as is not going to be merged. Sorry.

**Comment by golubvladimir** [comment]
@ivanmarban why ?

**Comment by ivanmarban** [comment]
As I said, I don't see the necessity of formatting log messages in Markdown or HTML

**Pull request closed without merging**
