### PR TITLE
Pass full data argument to formatMessage method

### PR DESCRIPTION
**Pull request by arnidan**

### CODE REVIEW

**Comment by arnidan** [comment]
@ivanmarban 

Hi, could you review the PR?

**Comment by ivanmarban** [comment]
I need to find some free time to review it. Sorry for the inconvenience. Thanks for your PR by the way :)

**Comment by ivanmarban** [comment]
Hi, I think this PR has the same behavior as [Winston's use of `info` object](https://github.com/winstonjs/winston#streams-objectmode-and-info-objects). Here is an example that does the same as your test code:

```javascript
const logger = require('winston')
const TelegramLogger = require('winston-telegram')

logger.add(
  new TelegramLogger({
    token: 'TELEGRAM_TOKEN',
    chatId: 'CHAT_ID',
    level: 'info',
    unique: true,
    formatMessage: function (options) {
      let message = options.message
      if (options.level === 'info') {
        message = '[Info] ' + message
      }

      if (options.metadata.superUrgent) {
        message += '!!!'
      }

      return message
    }
  })
)

const info = {
  level: 'info',
  message: 'Hey! Log something?',
  metadata: { superUrgent: true }
}

logger.log(info)

// Output: [Info] Hey! Log something?!!!
```

From my point of view, I see this feature redundant.

**Comment by arnidan** [comment]
Here you force to use the `metadata` param to send meta. But [winston doc](https://github.com/winstonjs/winston#streams-objectmode-and-info-objects) says:

> Properties besides level and message are considered as "meta"
> `const { level, message, ...meta } = info;`

There is also an example of usage metadata: https://github.com/winstonjs/winston/blob/master/examples/metadata.js

In the PR I tried not to break your logic and gave an option to use full info object

**Comment by ivanmarban** [comment]
Thanks. I will make a release as soon as I understand how to replace Travis CI in favor of Github actions.

**Pull request merged**
